#!/usr/bin/env bash

# Exit on first error
set -e;

# Load functions;
source $HOME/.local/bin/functions/drupal.sh;

# Check for Drupal installation;
drupal-install;

echo "Backup Drupal project database.";
read -p "Press [ENTER] to continue: ";

# Ask for backup directory;
read -e -p "Backup location (eg: ./): " BACKUP_DIR;
BACKUP_DIR=$(readlink -f $BACKUP_DIR);

# Create backup directory;
mkdir -p $BACKUP_DIR;

# Dump database to backup directory;
# Result file is gzipped and titled by timestamp;
drush sql-dump --gzip --result-file=$BACKUP_DIR/$(date +"%y%m%d%H%M%S").sql;
