#!/usr/bin/env bash

# Create Drupal archive without core;

# Exit on first error;
set -e;

# Load functions;
source $HOME/.local/bin/functions/drupal.sh;

# Check for Drupal installation;
drupal-install;

# Store current timestamp;
TIMESTAMP=$(date +"%y%m%d%H%M%S");

# Store backup directory;
echo "Export files and database.";
read -p "Press [ENTER] to continue: ";
read -e -p "Backup location: " DIR_BACKUP;
DIR_BACKUP=$(readlink -f $DIR_BACKUP);

# Create backup directory;
mkdir -p $DIR_BACKUP;

# Backing up;
drush archive-dump @sites --destination=$DIR_BACKUP/$TIMESTAMP.tar.gz --no-core;
