#!/usr/bin/env bash

# Exit on first error;
set -e;

# Load functions;
source $HOME/.local/bin/functions/drupal.sh;

# Check for Drupal installation;
drupal-install;

echo "Reset Admin password to 'password'";
read -p "Press [ENTER] to continue]: ";

read -p "User [admin]: ";
DRUPAL_USER=${DRUPAL_USER:-admin};

drush upwd $DRUPAL_USER --password=password;
