#!/usr/bin/env bash

# Fix file permissions;

# Exit on first error;
set -e;

# Load functions;
source $HOME/.local/bin/functions/drupal.sh;

# Check for Drupal installation;
drupal-install;

echo "Fix Drupal settings permissions.";
read -p "Press [ENTER] to continue";

chmod u+wx ./sites/*/ && chmod u+wx ./sites/*/settings.php;
