#!/usr/bin/env bash

# Enable development mode;

# Exit on first error;
set -e;

# Load functions
source $HOME/.local/bin/functions/drupal.sh;

# Check for Drupal installation;
drupal-install;

echo "Enable Drupal development environment.";
read -p "Press [ENTER] to continue: ";

# Helper function to disable configuration via Drush;
function _vset-dis () {
  drush vset $1 0
}

echo "Disabling caches..."
_vset-dis cache && \
  _vset-dis block_cache && \
  _vset-dis page_compression && \
  _vset-dis preprocess_css && \
  _vset-dis preprocess_js
