#!/usr/bin/env bash

# Fix permissions on directories;

# Exit on first error;
set -e;

# Load functions;
source $HOME/.local/bin/functions/drupal.sh;

# Check for Drupal installation;
drupal-install;

echo "Fix drupal installation file paths."
read -p "Press [ENTER] to continue: "

# Get current directory path;
CURRENT=$(basename $(pwd));

# Get parent directory path;
PARENT=$(basename $(readlink -f ../));

# Ensure we are in a multi-site directory;
if [[ "$PARENT" != "sites" ]]; then
  echo "Wrong directory."
  echo "Change directory to either default or your Drupal instance root."
  echo "EG: cd docroot/sites/example.com/"
  exit
fi

# Create and set file permissions for 'files';
mkdir -p files \
  && chgrp -R app files \
  && chmod -R g+w files;

# Set temporary FS configuration;
drush config-set system.file path.temporary /tmp -y;
